### ISSUE TITLE
Single server multi-gpu fine-tuning reports a timeout error.

### ISSUE THREAD

**Issue by XUSean0118** [OpenGVLab/GUI-Odyssey#5]
I get `Error: Some NCCL operations have failed or timed out` when I use the train.sh for finetuning.
I would like to ask if there are any related solutions or experiences.

**Comment by Lqf-HFNJU** [comment]
Hi, 
The error "Some NCCL operations have failed or timed out" can be caused by various factors. Based on my personal experience, it might be due to environment variables or the DeepSpeed ZERO optimization level. You could try adjusting the relevant parameters or provide more details for further assistance.

**Comment by Lqf-HFNJU** [comment]
Maybe you could try adjusting environment variables like NCCL_IB_HCA or NCCL_SOCKET_IFNAME based on your machine's configuration?
